import type { Metadata } from "next";
import { Inter } from "next/font/google";

// * Third Party
import { ThemeModeScript } from "flowbite-react";
import { Toaster } from "react-hot-toast";

// * CSS
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript mode="light" />
      </head>
      <body className={inter.className}>
        <>
          <Toaster position="top-right" />
          {children}
        </>
      </body>
    </html>
  );
}
